-- Baby Bet Board schema for Supabase
-- This project uses an invite-link board key as the shared secret.
-- If you want stricter protection later, add RLS policies on top of this schema.

create table if not exists public.baby_bet_board (
  board_key text primary key,
  predicted_date text not null default '',
  predicted_name text not null default '',
  prediction_note text not null default '',
  stake text not null default '',
  actual_date text not null default '',
  actual_name text not null default '',
  result_note text not null default '',
  updated_at timestamptz not null default now()
);

create table if not exists public.baby_bet_notes (
  id bigint generated by default as identity primary key,
  board_key text not null,
  created_at timestamptz not null default now(),
  text text not null
);

create index if not exists baby_bet_notes_board_key_created_at_idx
  on public.baby_bet_notes (board_key, created_at desc);
