-- Baby Bet Board schema for Supabase
-- This project now uses a single shared list. The `board_key` columns remain
-- for compatibility with existing data and older rows.
-- If you want stricter protection later, add RLS policies on top of this schema.

create table if not exists public.baby_bet_bets (
  id text primary key,
  board_key text not null,
  created_at timestamptz not null default now(),
  predicted_date text not null default '',
  predicted_name text not null default '',
  guessed_by text not null default '',
  guess_time text not null default '',
  actual_date text not null default '',
  actual_name text not null default '',
  result_note text not null default ''
);

create index if not exists baby_bet_bets_board_key_created_at_idx
  on public.baby_bet_bets (board_key, created_at desc);

alter table if exists public.baby_bet_bets
  add column if not exists guessed_by text not null default '',
  add column if not exists guess_time text not null default '';

alter table if exists public.baby_bet_bets
  drop column if exists prediction_note,
  drop column if exists stake;

create table if not exists public.baby_bet_board (
  board_key text primary key,
  predicted_date text not null default '',
  predicted_name text not null default '',
  guessed_by text not null default '',
  guess_time text not null default '',
  actual_date text not null default '',
  actual_name text not null default '',
  result_note text not null default '',
  updated_at timestamptz not null default now()
);

alter table if exists public.baby_bet_board
  add column if not exists guessed_by text not null default '',
  add column if not exists guess_time text not null default '';

alter table if exists public.baby_bet_board
  drop column if exists prediction_note,
  drop column if exists stake;

create table if not exists public.baby_bet_notes (
  id bigint generated by default as identity primary key,
  board_key text not null,
  created_at timestamptz not null default now(),
  text text not null
);

create index if not exists baby_bet_notes_board_key_created_at_idx
  on public.baby_bet_notes (board_key, created_at desc);
